//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesDetails
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeDetail
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Name is required!")]
        public string Name { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile Number")]
        [Required(ErrorMessage = "Mobile Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered Mobile No. format is not valid.")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Email is Required !")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                       @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                       @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                       ErrorMessage = "Email is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Technical Skill is required !")]
        public string TechnicalSkills { get; set; }
        [Required(ErrorMessage = "Project Detail is required !")]
        public string ProjectDetails { get; set; }
        [Required(ErrorMessage = "Experience is required !")]
        public string RelevantExperience { get; set; }
    }
}
